# Generated by Django 5.1.1 on 2024-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='city_associated',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
