# Generated by Django 5.1.1 on 2024-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_rental_city_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('on_sale', 'En venta'), ('booked', 'Reservado'), ('sold', 'Vendido')], default='on_sale', max_length=10),
        ),
    ]
