# Generated by Django 5.1.1 on 2024-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('on_sale', 'Anuncio activo'), ('booked', 'Reservado'), ('sold', 'Ya alquilado')], default='on_sale', max_length=10),
        ),
    ]
