# Generated by Django 5.1.1 on 2025-01-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_city_admin',
            field=models.BooleanField(default=False),
        ),
    ]
