# Generated by Django 5.1.1 on 2024-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_visibility',
            field=models.CharField(choices=[('public', 'Pública'), ('private', 'Privada')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_age',
            field=models.BooleanField(default=True),
        ),
    ]
