# Generated by Django 5.1.1 on 2024-11-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_product_images_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
