# Generated by Django 5.1.1 on 2024-11-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser_selected_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city_associated',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rental',
            name='city_associated',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
