# Generated by Django 5.1.1 on 2024-11-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_city_associated_rental_city_associated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='images',
        ),
        migrations.CreateModel(
            name='RentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_pictures/')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_images', to='main.rental')),
            ],
        ),
    ]
