# Generated by Django 5.1.1 on 2024-11-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_rental_images_rentalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalimage',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.rental'),
        ),
    ]
