# Generated by Django 5.1.1 on 2024-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_rentalimage_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
