# Generated by Django 5.1.1 on 2024-11-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rentalfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.rentalfeatures'),
        ),
    ]
