# Generated by Django 5.1.1 on 2024-11-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rental_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalFeatures',
            new_name='RentalFeature',
        ),
    ]
