# Generated by Django 5.1.1 on 2024-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_rentalfeatures_rentalfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='city_associated',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
