# Generated by Django 5.1.1 on 2024-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_rental_city_associated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalfeature',
            name='feature',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
