# Generated by Django 5.1.1 on 2024-11-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_rentalfeature_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='features',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rentalimage',
            name='rental',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='RentalFeature',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='RentalImage',
        ),
    ]
