# Generated by Django 5.1.1 on 2024-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rentalfeature_product_productimage_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='money_associated',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='money_associated',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
