# Generated by Django 5.1.1 on 2024-11-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_product_money_associated_rental_money_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='see_own_products',
            field=models.BooleanField(default=False),
        ),
    ]
