# Generated by Django 5.1.1 on 2024-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_product_created_at_alter_rental_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
