# Generated by Django 5.1.1 on 2024-11-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_product_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
