# Generated by Django 5.1.1 on 2024-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rental_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
