# Generated by Django 5.1.1 on 2024-11-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_product_currency_rental_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='currency',
        ),
    ]
