# Generated by Django 5.1.1 on 2024-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_product_currency_remove_rental_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlighted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
