# Generated by Django 5.1.1 on 2024-11-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_product_highlighted_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='highlighted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
