# Generated by Django 5.1.1 on 2024-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rental_highlighted_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='money_associated',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
