# Generated by Django 5.1.1 on 2024-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_rental_money_associated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='money_associated',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
