# Generated by Django 5.1.1 on 2024-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_rental_money_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
