# Generated by Django 5.1.1 on 2024-12-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together=set(),
        ),
    ]
