# Generated by Django 5.1.1 on 2024-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_chatrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='initial_message',
            field=models.TextField(blank=True),
        ),
    ]
