# Generated by Django 5.1.1 on 2024-12-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_chatrequest_product'),
        ('market', '0005_product_buyer_rental_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='associated_chats', to='market.product'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
    ]
