# Generated by Django 5.1.1 on 2024-12-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_chat_products_message_is_system_message'),
        ('market', '0005_product_buyer_rental_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='rentings',
            field=models.ManyToManyField(blank=True, related_name='rentings_associated_chats', to='market.rental'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='renting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentings_chatrequests', to='market.rental'),
        ),
        migrations.AddField(
            model_name='message',
            name='renting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renting_messages', to='market.rental'),
        ),
    ]
