# Generated by Django 5.1.1 on 2024-12-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_chat_rentings_chatrequest_renting_message_renting'),
        ('market', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_messages', to='market.product'),
        ),
    ]
