# Generated by Django 5.1.1 on 2024-12-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='community.groupchat'),
        ),
    ]
