# Generated by Django 5.1.1 on 2024-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_chat_pictures/'),
        ),
    ]
