# Generated by Django 5.1.1 on 2024-12-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_groupchat_description_groupchat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='is_group',
            field=models.BooleanField(default=True),
        ),
    ]
