# Generated by Django 5.1.1 on 2024-12-26 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_chat_is_group_groupchat_is_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='members',
        ),
        migrations.CreateModel(
            name='GroupChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('normal', 'Normal'), ('external', 'Externo'), ('admin', 'Administrador')], default='normal', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.groupchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group_chat')},
            },
        ),
    ]
