# Generated by Django 5.1.1 on 2024-12-26 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_remove_groupchat_members_groupchatmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_chats', through='community.GroupChatMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
