# Generated by Django 5.1.1 on 2024-12-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_groupchat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='initial_message',
            field=models.TextField(blank=True),
        ),
    ]
