# Generated by Django 5.1.1 on 2024-12-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_groupchat_initial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='is_friends_group',
            field=models.BooleanField(default=False),
        ),
    ]
