# Generated by Django 5.1.1 on 2024-12-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_groupchat_is_friends_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='group_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to='community.groupchat'),
        ),
    ]
