# Generated by Django 5.1.1 on 2025-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='is_delete_request',
            field=models.BooleanField(default=False),
        ),
    ]
