# Generated by Django 5.1.1 on 2025-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_chatrequest_is_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='is_event_group',
            field=models.BooleanField(default=False),
        ),
    ]
