# Generated by Django 5.1.1 on 2025-01-28 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_groupchat_is_event_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='chat_members',
            field=models.ManyToManyField(related_name='group_chats', through='community.ChatMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
